---
# yaml-language-server: $schema=schema/zarf-config-distro-schema.json
log_level: info
log_format: console
tmp_dir: /tmp
zarf_cache: ~/.cache/cargoship
timeout: 60m
distro:
  type: rke2
  oci_concurrency: 10
  concurrency: 300
  worker_concurrency: 5
  hosts: true
  firewall: true
  fapolicyd: true
  output: ~/zarf
