// Copyright 2026 colonel-byte
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package osv manages osv-scanner.toml overrides in vendor/ to prevent non-Go manifests
// from degrading OpenSSF Scorecard Vulnerability checks.
package osv

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Override is one osv-scanner.toml configuration that suppresses false-positive vulnerabilities.
type Override struct {
	Dir       string
	Manifest  string
	Ecosystem string
	What      string
}

// Overrides is the full set of non-Go manifests in vendor/.
var Overrides = []Override{
	{
		Dir:       "vendor/golang.org/x/telemetry",
		Manifest:  "package-lock.json",
		Ecosystem: "npm",
		What:      "the devDependencies of the web UI x/telemetry serves from its own repository",
	},
	{
		Dir:       "vendor/github.com/theupdateframework/go-tuf",
		Manifest:  "requirements-test.txt",
		Ecosystem: "PyPI",
		What:      "the Python harness go-tuf runs its own conformance tests under",
	},
	{
		Dir:       "vendor/github.com/txn2/txeh",
		Manifest:  "requirements-docs.txt",
		Ecosystem: "PyPI",
		What:      "the MkDocs toolchain that builds txeh's documentation site",
	},
	{
		Dir:       "vendor/go.opentelemetry.io/otel",
		Manifest:  "requirements.txt",
		Ecosystem: "PyPI",
		What:      "the codespell pin otel's own spelling check installs",
	},
}

// OverrideName is the filename osv-scanner looks for next to a manifest.
const OverrideName = "osv-scanner.toml"

func ecosystemLanguage(ecosystem string) string {
	switch ecosystem {
	case "npm":
		return "JavaScript"
	case "PyPI":
		return "Python"
	default:
		return ecosystem
	}
}

const commentWidth = 96

func comment(paragraphs ...string) string {
	var b strings.Builder
	for i, p := range paragraphs {
		if i > 0 {
			b.WriteString("#\n")
		}
		line := "#"
		for _, word := range strings.Fields(p) {
			if len(line)+1+len(word) > commentWidth {
				b.WriteString(line + "\n")
				line = "#"
			}
			line += " " + word
		}
		b.WriteString(line + "\n")
	}
	return b.String()
}

// OverrideContent renders the osv-scanner.toml for one override.
func OverrideContent(o Override) string {
	return comment(
		`Generated by "mage dev:vendor". Do not edit, and do not delete.`,
		fmt.Sprintf(`%s here is %s. It is not a cargoship dependency -- go mod vendor copies it in `+
			`because it sits in a vendored module's directory, and nothing it names is compiled, `+
			`executed or shipped.`, o.Manifest, o.What),
		`OpenSSF Scorecard runs osv-scanner over the whole checkout and scores Vulnerabilities as `+
			`ten minus the number of findings, so without this file every advisory ever filed `+
			`against those packages costs the repository a point. See `+
			`docs/agent/choice-osv-vendor-overrides.md.`,
	) + fmt.Sprintf(`
[[PackageOverrides]]
ecosystem = %q
ignore = true
reason = %q
`,
		o.Ecosystem,
		ecosystemLanguage(o.Ecosystem)+" tooling vendored alongside a Go module; not built, run or shipped by cargoship",
	)
}

// WriteOverrides writes every override into vendor/.
func WriteOverrides() error {
	for _, o := range Overrides {
		if _, err := os.Stat(filepath.Join(o.Dir, o.Manifest)); err != nil {
			return fmt.Errorf("osv override for %s: %w -- the manifest is gone, so drop the entry from Overrides", o.Dir, err)
		}
		path := filepath.Join(o.Dir, OverrideName)
		if err := os.WriteFile(path, []byte(OverrideContent(o)), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
		fmt.Println("wrote", path)
	}
	return nil
}

// ForeignManifest reports whether name is a dependency manifest for an ecosystem other than Go.
func ForeignManifest(name string) bool {
	switch name {
	case "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lock",
		"Pipfile.lock", "poetry.lock", "pdm.lock", "uv.lock",
		"Gemfile.lock", "Cargo.lock", "composer.lock", "mix.lock",
		"pubspec.lock", "conan.lock", "gradle.lockfile", "packages.lock.json",
		"pom.xml":
		return true
	}
	return strings.Contains(name, "requirements") && strings.HasSuffix(name, ".txt")
}

// VerifyVendor checks that vendor/ contains all required overrides and no uncovered manifests.
func VerifyVendor() error {
	var problems []string

	covered := make(map[string]string, len(Overrides))
	for _, o := range Overrides {
		covered[filepath.Clean(o.Dir)] = o.Ecosystem

		path := filepath.Join(o.Dir, OverrideName)
		got, err := os.ReadFile(path)
		if err != nil {
			problems = append(problems, fmt.Sprintf("%s is missing (%v)", path, err))
			continue
		}
		if string(got) != OverrideContent(o) {
			problems = append(problems, fmt.Sprintf("%s does not match expected override content", path))
		}
	}

	err := filepath.WalkDir("vendor", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !ForeignManifest(d.Name()) {
			return nil
		}
		if _, ok := covered[filepath.Dir(path)]; !ok {
			problems = append(problems, fmt.Sprintf("%s is a non-Go dependency manifest with no entry in Overrides", path))
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("walking vendor: %w", err)
	}

	if len(problems) > 0 {
		return fmt.Errorf("vendored osv-scanner overrides are out of date:\n  %s\n"+
			"a missing or mismatched override is rewritten by `mage dev:writeOSVOverrides`; "+
			"an uncovered manifest needs an entry in Overrides first",
			strings.Join(problems, "\n  "))
	}
	fmt.Printf("%d osv-scanner overrides present and current\n", len(Overrides))
	return nil
}
