// Copyright 2026 colonel-byte
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package util provides general filesystem, git, markdown, and execution helpers for magefiles.
package util

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode/utf8"

	"github.com/colonel-byte/cargoship/config"
	goyaml "github.com/goccy/go-yaml"
	"github.com/magefile/mage/sh"
	"github.com/nao1215/markdown"
)

// GeneratedBanner marks a page as generator output.
const GeneratedBanner = "<!-- Page generated by Cargoship; DO NOT EDIT -->"

// GitCommit returns the short commit of the checkout being built, suffixed with "-dirty" when
// the working tree has uncommitted changes. When the commit cannot be resolved, it returns
// config.UnsetCLICommit.
func GitCommit() string {
	commit, err := sh.Output("git", "rev-parse", "--short", "HEAD")
	if err != nil {
		return config.UnsetCLICommit
	}

	commit = strings.TrimSpace(commit)
	if commit == "" {
		return config.UnsetCLICommit
	}

	if dirty, err := sh.Output("git", "status", "--porcelain"); err == nil && strings.TrimSpace(dirty) != "" {
		commit += "-dirty"
	}

	return commit
}

// CleanBuild removes compiled binary artifacts under build/.
func CleanBuild() error {
	files, _ := filepath.Glob("build/cargoship_*") //nolint:errcheck // the only error is a malformed pattern, and this one is a constant
	for _, f := range files {
		fmt.Println("removing: " + f)
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	return nil
}

// RenderYAMLValue renders a default value the way it is written in YAML.
func RenderYAMLValue(value any) string {
	if value == nil {
		return "null"
	}
	if s, ok := value.(string); ok {
		if s == "" {
			return `""`
		}
		return s
	}
	out, err := goyaml.Marshal(value)
	if err != nil {
		return fmt.Sprintf("(unrenderable: %v)", err)
	}
	return strings.TrimSpace(string(out))
}

// EscapeAngleBrackets replaces literal "<" and ">" with HTML entities.
func EscapeAngleBrackets(s string) string {
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}

// PaddedTable renders a table in the aligned form required by repo style guides.
func PaddedTable(header []string, rows [][]string) []string {
	escaped := make([][]string, 0, len(rows)+1)
	width := make([]int, len(header))
	for _, row := range append([][]string{header}, rows...) {
		cells := make([]string, len(header))
		for i := range cells {
			if i < len(row) {
				cells[i] = markdown.EscapeTableCell(EscapeAngleBrackets(row[i]))
			}
			if n := utf8.RuneCountInString(cells[i]); n > width[i] {
				width[i] = n
			}
		}
		escaped = append(escaped, cells)
	}

	line := func(cells []string) string {
		var b strings.Builder
		b.WriteString("|")
		for i, cell := range cells {
			b.WriteString(" ")
			b.WriteString(cell)
			b.WriteString(strings.Repeat(" ", width[i]-utf8.RuneCountInString(cell)))
			b.WriteString(" |")
		}
		return b.String()
	}

	delimiter := make([]string, len(header))
	for i, w := range width {
		delimiter[i] = strings.Repeat("-", w)
	}

	out := make([]string, 0, len(escaped)+1)
	out = append(out, line(escaped[0]))
	out = append(out, line(delimiter))
	for _, row := range escaped[1:] {
		out = append(out, line(row))
	}
	return out
}
