// Copyright 2026 colonel-byte
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/colonel-byte/cargoship/src/api/zarf.dev/v1alpha1/cluster"
	"github.com/colonel-byte/cargoship/src/cmd"
	"github.com/colonel-byte/cargoship/src/pkg/action"
	"github.com/colonel-byte/cargoship/src/pkg/phase"
	"github.com/colonel-byte/cargoship/src/types/distrocfg"
	"github.com/magefile/mage/mg"
	"github.com/nao1215/markdown"
	"github.com/spf13/cobra/doc"
)

type (
	Generate mg.Namespace
)

// Document creates the docs for this repo
func (Generate) Document() error {
	rootCmd := cmd.NewCargoshipCommand()
	rootCmd.DisableAutoGenTag = true

	docsDirs := []string{
		"./docs/actions",
		"./docs/commands",
	}

	for _, dir := range docsDirs {
		if err := os.RemoveAll(dir); err != nil {
			return err
		}
		if err := os.MkdirAll(dir, 0o775); err != nil {
			return err
		}
	}

	if err := doc.GenMarkdownTreeCustom(rootCmd, "./docs/commands", prependTitle, linkHandler); err != nil {
		return err
	}
	if err := phaseApply(); err != nil {
		return err
	}
	if err := phaseReset(); err != nil {
		return err
	}
	if err := phaseKubeConfig(); err != nil {
		return err
	}
	if err := phasePrepare(); err != nil {
		return err
	}
	if err := generateSummary(); err != nil {
		return err
	}

	return nil
}

func generateSummary() error {
	fmt.Println("docs/SUMMARY.md")
	var builder strings.Builder

	md := markdown.NewMarkdown(&builder).H1("Index")
	md = md.PlainText("\n[main](index.md)\n")

	md = md.H1("Command")
	md = md.PlainText("\n- [cargoship](commands/cargoship.md)")

	if sub, err := getSubcommands(); err == nil {
		for _, s := range sub {
			md = md.PlainText(s)
		}
	}

	md = md.PlainText("\n-----------\n")
	md = md.H1("Phases")
	md = md.PlainText("")

	if phases, err := getPhases(); err == nil {
		for _, p := range phases {
			md = md.PlainText(p)
		}
	}

	md = md.PlainText(`
-----------

[changelog](changelog.md)
`)

	if err := md.Build(); err != nil {
		return err
	}

	return os.WriteFile("docs/SUMMARY.md", []byte(builder.String()), 0644)
}

func getSubcommands() ([]string, error) {
	list := []string{}

	re, err := regexp.Compile(`cargoship_.+\.md`)
	if err != nil {
		return []string{}, err
	}

	sub, err := regexp.Compile(`cargoship_(.+)\.md`)
	if err != nil {
		return []string{}, err
	}

	entries, err := os.ReadDir("docs/commands")
	if err != nil {
		return []string{}, err
	}

	for _, entry := range entries {
		if !entry.IsDir() && re.MatchString(entry.Name()) {
			com := sub.FindStringSubmatch(entry.Name())
			list = append(list, fmt.Sprintf("  - [%s](commands/%s)", com[1], entry.Name()))
		}
	}

	return list, nil
}

func getPhases() ([]string, error) {
	list := []string{}

	re, err := regexp.Compile(`.+\.md`)
	if err != nil {
		return []string{}, err
	}

	sub, err := regexp.Compile(`(.+)\.md`)
	if err != nil {
		return []string{}, err
	}

	entries, err := os.ReadDir("docs/actions")
	if err != nil {
		return []string{}, err
	}

	for _, entry := range entries {
		if !entry.IsDir() && re.MatchString(entry.Name()) {
			com := sub.FindStringSubmatch(entry.Name())
			list = append(list, fmt.Sprintf("- [%s](actions/%s)", com[1], entry.Name()))
		}
	}

	return list, nil
}

func prependTitle(s string) string {
	fmt.Println(s)
	return `<!-- Page generated by Cargoship; DO NOT EDIT -->

`
}

func linkHandler(link string) string {
	return "./" + link[:len(link)-3] + ".md"
}

func phaseComment(mk *markdown.Markdown, p phase.Phase) {
	mk.OrderedList(p.Title())
	mk.PlainTextf("    - %s", p.Explanation())
}

func phaseApply() error {
	apply := action.NewApply(action.ApplyOptions{
		Manager: &phase.Manager{
			DistroID: distrocfg.DistroRKE2,
			Config: &cluster.ZarfCluster{
				Metadata: cluster.ZarfClusterMetadata{
					Name: "gen-docs",
				},
			},
		},
	})

	fmt.Println("docs/actions/apply.md")
	f, err := os.Create("docs/actions/apply.md")
	if err != nil {
		return err
	}
	defer func() {
		if err := f.Close(); err != nil {
			panic(err)
		}
	}()

	applyDoc := markdown.NewMarkdown(f)

	applyDoc.H2("apply phases")

	for _, p := range apply.Phases {
		phaseComment(applyDoc, p)
	}

	applyDoc.PlainTextf("")

	return applyDoc.Build()
}

func phaseReset() error {
	reset := action.NewReset(action.ResetOptions{
		Manager: &phase.Manager{
			DistroID: distrocfg.DistroRKE2,
		},
	})

	fmt.Println("docs/actions/reset.md")
	f, err := os.Create("docs/actions/reset.md")
	if err != nil {
		return err
	}
	defer func() {
		if err := f.Close(); err != nil {
			panic(err)
		}
	}()

	resetDoc := markdown.NewMarkdown(f)

	resetDoc.H2("reset phases")

	for _, p := range reset.Phases {
		phaseComment(resetDoc, p)
	}

	resetDoc.PlainTextf("")

	return resetDoc.Build()
}

func phaseKubeConfig() error {
	kube := action.NewKubeConfig(action.KubeConfigOptions{
		Manager: &phase.Manager{
			DistroID: distrocfg.DistroRKE2,
			Config: &cluster.ZarfCluster{
				Metadata: cluster.ZarfClusterMetadata{
					Name: "gen-docs",
				},
			},
		},
	})

	fmt.Println("docs/actions/kube-config.md")
	f, err := os.Create("docs/actions/kube-config.md")
	if err != nil {
		return err
	}
	defer func() {
		if err := f.Close(); err != nil {
			panic(err)
		}
	}()

	resetDoc := markdown.NewMarkdown(f)

	resetDoc.H2("kube-config phases")

	for _, p := range kube.Phases {
		phaseComment(resetDoc, p)
	}

	resetDoc.PlainTextf("")

	return resetDoc.Build()
}

func phasePrepare() error {
	kube := action.NewPrepare(action.PrepareOptions{})

	fmt.Println("docs/actions/prepare.md")
	f, err := os.Create("docs/actions/prepare.md")
	if err != nil {
		return err
	}
	defer func() {
		if err := f.Close(); err != nil {
			panic(err)
		}
	}()

	resetDoc := markdown.NewMarkdown(f)

	resetDoc.H2("prepare phases")

	for _, p := range kube.Phases {
		phaseComment(resetDoc, p)
	}

	resetDoc.PlainTextf("")

	return resetDoc.Build()
}
