---
- name: Fetch zarf state from cluster
  colonel_byte.zarf.zarf_state_info:
    kubeconfig: "{{ zarf_kubeconfig | default(omit) if (zarf_kubeconfig | length > 0) else omit }}"
    zarf_binary: "{{ zarf_binary }}"
    namespace: "{{ zarf_namespace }}"
  delegate_to: "{{ zarf_delegate_to }}"
  run_once: true
  register: _zarf_state_fetch

- name: Set zarf_state fact
  ansible.builtin.set_fact:
    zarf_state: "{{ _zarf_state_fetch.state }}"
  run_once: true
