// Copyright 2026 colonel-byte
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// package main is used to generate the markdown docs for the cli
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/colonel-byte/cargoship/src/cmd"
	"github.com/colonel-byte/cargoship/src/pkg/action"
	"github.com/colonel-byte/cargoship/src/pkg/phase"
	"github.com/colonel-byte/cargoship/src/types/distrocfg"
	"github.com/nao1215/markdown"
	"github.com/spf13/cobra/doc"

	// anonymous import is needed to load the distro configurers
	_ "github.com/colonel-byte/cargoship/src/types/distrocfg"
)

func main() {
	rootCmd := cmd.NewCargoshipCommand()
	rootCmd.DisableAutoGenTag = true

	if err := os.RemoveAll("./docs"); err != nil {
		panic(err)
	}
	if err := os.MkdirAll("./docs/commands", 0o775); err != nil {
		panic(err)
	}
	if err := os.MkdirAll("./docs/actions", 0o775); err != nil {
		panic(err)
	}

	err := doc.GenMarkdownTreeCustom(rootCmd, "./docs/commands", prependTitle, linkHandler)
	if err != nil {
		panic(err)
	}

	phaseApply()

	if err := markdown.GenerateIndex(
		"./docs",
		markdown.WithTitle("Index"),
		markdown.WithDescription([]string{
			"automatically generated document for the `cargoship` command",
		}),
	); err != nil {
		panic(err)
	}
}

func prependTitle(s string) string {
	fmt.Println(s)

	name := filepath.Base(s)

	// strip .md extension
	name = name[:len(name)-3]

	// replace _ with space
	title := strings.ReplaceAll(name, "_", " ")

	return fmt.Sprintf(`---
title: %s
description: Cargoship CLI command reference for <code>%s</code>.
tableOfContents: false
---

<!-- Page generated by Cargoship; DO NOT EDIT -->

`, title, title)
}

func linkHandler(link string) string {
	return "./" + link[:len(link)-3] + ".md"
}

func phaseComment(mk *markdown.Markdown, p phase.Phase) {
	mk.OrderedList(p.Title())
	mk.PlainTextf("    - %s", p.Explanation())
}

func phaseApply() error {
	apply := action.NewApply(action.ApplyOptions{
		Manager: &phase.Manager{
			DistroID: distrocfg.DistroRKE2,
		},
	})

	f, err := os.Create("docs/actions/apply.md")
	if err != nil {
		return err
	}
	defer func() {
		if err := f.Close(); err != nil {
			panic(err)
		}
	}()

	applyDoc := markdown.NewMarkdown(f)

	applyDoc.H2("apply phases")

	for _, p := range apply.Phases {
		phaseComment(applyDoc, p)
	}

	applyDoc.PlainTextf("")

	return applyDoc.Build()
}
