// Copyright 2026 colonel-byte
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/colonel-byte/cargoship/src/cmd"
	"github.com/spf13/cobra/doc"
)

func main() {
	rootCmd := cmd.NewCargoshipCommand()
	rootCmd.DisableAutoGenTag = true

	if err := os.RemoveAll("./docs/commands"); err != nil {
		panic(err)
	}
	if err := os.MkdirAll("./docs/commands", 0o775); err != nil {
		panic(err)
	}

	prependTitle := func(s string) string {
		fmt.Println(s)

		name := filepath.Base(s)

		// strip .md extension
		name = name[:len(name)-3]

		// replace _ with space
		title := strings.ReplaceAll(name, "_", " ")

		return fmt.Sprintf(`---
title: %s
description: Cargoship CLI command reference for <code>%s</code>.
tableOfContents: false
---

<!-- Page generated by Cargoship; DO NOT EDIT -->

`, title, title)
	}

	linkHandler := func(link string) string {
		return "/commands/" + link[:len(link)-3] + "/"
	}

	doc.GenMarkdownTreeCustom(rootCmd, "./docs/commands", prependTitle, linkHandler)
}
