---
name: Basic build

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the binary and init package
  build-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -mod=vendor -ldflags="-s -w" -v -o cargoship main.go

      - name: Upload binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cargoship
          path: cargoship
